Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -40,7 +40,7 @@ jobs:
         run: |
           semgrep --config=auto --json --output semgrep-results.json
           if grep -qE "(MEDIUM|HIGH|CRITICAL)" semgrep-results.json; then
-            cat semgrep-results.json | jq  -c '[.results[] | {message: .extra.message , secret: .extra.lines , impact: .extra.metadata.impact}]' | jq  >&2
+            cat semgrep-results.json | jq  -c '[.results[] | {message: .extra.message , line: .extra.lines , impact: .extra.metadata.impact}]' | jq  >&2
             exit 1
           fi
         continue-on-error: false
@@ -50,3 +50,10 @@ jobs:
         run: gitleaks detect --verbose --redact -f gitleaks-results.txt
         # Whether to continue if secrets got detected
         continue-on-error: false
+    
+    - name: Fail if any step failed
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "One or more steps failed"
+            exit 1
+          fi
